import { PermissionName, Role } from "../../generated/prisma/client";

type DefaultPermissions = {
    [key in Role]: PermissionName[];
};

export const DEFAULT_PERMISSIONS: DefaultPermissions = {
    [Role.SUPER_ADMIN]: [
        PermissionName.MANAGE_ORG,
        PermissionName.MANAGE_SUBSCRIPTION,
        PermissionName.VIEW_BILLING,
        PermissionName.INVITE_USERS,
        PermissionName.VIEW_ALL_USERS,
        PermissionName.BAN_USER,
        PermissionName.ASSIGN_ROLE,
        PermissionName.CREATE_PROJECT,
        PermissionName.UPDATE_PROJECT,
        PermissionName.DELETE_PROJECT,
        PermissionName.ASSIGN_PROJECT_MANAGER,
        PermissionName.VIEW_ALL_PROJECTS,
        PermissionName.CREATE_TASK,
        PermissionName.ASSIGN_TASK,
        PermissionName.UPDATE_TASK,
        PermissionName.DELETE_TASK,
        PermissionName.COMMENT_TASK,
        PermissionName.VIEW_PRIVATE_TASKS,
        PermissionName.CHANGE_TASK_STATUS,
        PermissionName.CREATE_SUBTASK,
        PermissionName.MARK_SUBTASK_DONE,
        PermissionName.USE_AI_ASSIGNMENT,
        PermissionName.VIEW_AI_LOG,
        PermissionName.LOG_TIME,
        PermissionName.VIEW_TIME_REPORT,
        PermissionName.CREATE_BADGE,
        PermissionName.ASSIGN_BADGE,
        PermissionName.VIEW_BADGE_HISTORY,
        PermissionName.VIEW_DASHBOARD,
        PermissionName.UPDATE_PROFILE,
        PermissionName.VIEW_NOTIFICATIONS,
    ],
    [Role.OWNER]: [
        PermissionName.MANAGE_ORG,
        PermissionName.MANAGE_SUBSCRIPTION,
        PermissionName.VIEW_BILLING,
        PermissionName.INVITE_USERS,
        PermissionName.VIEW_ALL_USERS,
        PermissionName.BAN_USER,
        PermissionName.ASSIGN_ROLE,
        PermissionName.CREATE_PROJECT,
        PermissionName.UPDATE_PROJECT,
        PermissionName.DELETE_PROJECT,
        PermissionName.ASSIGN_PROJECT_MANAGER,
        PermissionName.VIEW_ALL_PROJECTS,
        PermissionName.CREATE_TASK,
        PermissionName.ASSIGN_TASK,
        PermissionName.UPDATE_TASK,
        PermissionName.DELETE_TASK,
        PermissionName.COMMENT_TASK,
        PermissionName.VIEW_PRIVATE_TASKS,
        PermissionName.CHANGE_TASK_STATUS,
        PermissionName.CREATE_SUBTASK,
        PermissionName.MARK_SUBTASK_DONE,
        PermissionName.USE_AI_ASSIGNMENT,
        PermissionName.VIEW_AI_LOG,
        PermissionName.LOG_TIME,
        PermissionName.VIEW_TIME_REPORT,
        PermissionName.CREATE_BADGE,
        PermissionName.ASSIGN_BADGE,
        PermissionName.VIEW_BADGE_HISTORY,
        PermissionName.VIEW_DASHBOARD,
        PermissionName.UPDATE_PROFILE,
        PermissionName.VIEW_NOTIFICATIONS,
    ],
    [Role.PROJECT_MANAGER]: [
        PermissionName.INVITE_USERS,
        PermissionName.VIEW_ALL_USERS,
        PermissionName.CREATE_PROJECT,
        PermissionName.UPDATE_PROJECT,
        PermissionName.VIEW_ALL_PROJECTS,
        PermissionName.CREATE_TASK,
        PermissionName.ASSIGN_TASK,
        PermissionName.UPDATE_TASK,
        PermissionName.DELETE_TASK,
        PermissionName.COMMENT_TASK,
        PermissionName.VIEW_PRIVATE_TASKS,
        PermissionName.CHANGE_TASK_STATUS,
        PermissionName.CREATE_SUBTASK,
        PermissionName.MARK_SUBTASK_DONE,
        PermissionName.LOG_TIME,
        PermissionName.VIEW_TIME_REPORT,
        PermissionName.VIEW_DASHBOARD,
        PermissionName.UPDATE_PROFILE,
        PermissionName.VIEW_NOTIFICATIONS,
    ],
    [Role.TEAM_LEAD]: [
        PermissionName.VIEW_ALL_USERS,
        PermissionName.CREATE_TASK,
        PermissionName.ASSIGN_TASK,
        PermissionName.UPDATE_TASK,
        PermissionName.COMMENT_TASK,
        PermissionName.CHANGE_TASK_STATUS,
        PermissionName.CREATE_SUBTASK,
        PermissionName.MARK_SUBTASK_DONE,
        PermissionName.LOG_TIME,
        PermissionName.VIEW_TIME_REPORT,
        PermissionName.VIEW_DASHBOARD,
        PermissionName.UPDATE_PROFILE,
        PermissionName.VIEW_NOTIFICATIONS,
    ],
    [Role.SENIOR_EMPLOYEE]: [
        PermissionName.COMMENT_TASK,
        PermissionName.CHANGE_TASK_STATUS,
        PermissionName.CREATE_SUBTASK,
        PermissionName.MARK_SUBTASK_DONE,
        PermissionName.LOG_TIME,
        PermissionName.VIEW_TIME_REPORT,
        PermissionName.VIEW_DASHBOARD,
        PermissionName.UPDATE_PROFILE,
        PermissionName.VIEW_NOTIFICATIONS,
    ],
    [Role.EMPLOYEE]: [
        PermissionName.COMMENT_TASK,
        PermissionName.CHANGE_TASK_STATUS,
        PermissionName.MARK_SUBTASK_DONE,
        PermissionName.LOG_TIME,
        PermissionName.VIEW_DASHBOARD,
        PermissionName.UPDATE_PROFILE,
        PermissionName.VIEW_NOTIFICATIONS,
    ],
    [Role.INTERN]: [
        PermissionName.VIEW_DASHBOARD,
        PermissionName.UPDATE_PROFILE,
        PermissionName.VIEW_NOTIFICATIONS,
    ],
    [Role.VISITOR]: [
        PermissionName.VIEW_DASHBOARD,
    ],
}; 